// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: baseledger/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b223a452b70176, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b223a452b70176, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetBaseledgerTransactionRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetBaseledgerTransactionRequest) Reset()         { *m = QueryGetBaseledgerTransactionRequest{} }
func (m *QueryGetBaseledgerTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBaseledgerTransactionRequest) ProtoMessage()    {}
func (*QueryGetBaseledgerTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b223a452b70176, []int{2}
}
func (m *QueryGetBaseledgerTransactionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBaseledgerTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBaseledgerTransactionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBaseledgerTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBaseledgerTransactionRequest.Merge(m, src)
}
func (m *QueryGetBaseledgerTransactionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBaseledgerTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBaseledgerTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBaseledgerTransactionRequest proto.InternalMessageInfo

func (m *QueryGetBaseledgerTransactionRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetBaseledgerTransactionResponse struct {
	BaseledgerTransaction BaseledgerTransaction `protobuf:"bytes,1,opt,name=BaseledgerTransaction,proto3" json:"BaseledgerTransaction"`
}

func (m *QueryGetBaseledgerTransactionResponse) Reset()         { *m = QueryGetBaseledgerTransactionResponse{} }
func (m *QueryGetBaseledgerTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBaseledgerTransactionResponse) ProtoMessage()    {}
func (*QueryGetBaseledgerTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b223a452b70176, []int{3}
}
func (m *QueryGetBaseledgerTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBaseledgerTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBaseledgerTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBaseledgerTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBaseledgerTransactionResponse.Merge(m, src)
}
func (m *QueryGetBaseledgerTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBaseledgerTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBaseledgerTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBaseledgerTransactionResponse proto.InternalMessageInfo

func (m *QueryGetBaseledgerTransactionResponse) GetBaseledgerTransaction() BaseledgerTransaction {
	if m != nil {
		return m.BaseledgerTransaction
	}
	return BaseledgerTransaction{}
}

type QueryAllBaseledgerTransactionRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBaseledgerTransactionRequest) Reset()         { *m = QueryAllBaseledgerTransactionRequest{} }
func (m *QueryAllBaseledgerTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllBaseledgerTransactionRequest) ProtoMessage()    {}
func (*QueryAllBaseledgerTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b223a452b70176, []int{4}
}
func (m *QueryAllBaseledgerTransactionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBaseledgerTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBaseledgerTransactionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBaseledgerTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBaseledgerTransactionRequest.Merge(m, src)
}
func (m *QueryAllBaseledgerTransactionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBaseledgerTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBaseledgerTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBaseledgerTransactionRequest proto.InternalMessageInfo

func (m *QueryAllBaseledgerTransactionRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllBaseledgerTransactionResponse struct {
	BaseledgerTransaction []BaseledgerTransaction `protobuf:"bytes,1,rep,name=BaseledgerTransaction,proto3" json:"BaseledgerTransaction"`
	Pagination            *query.PageResponse     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBaseledgerTransactionResponse) Reset()         { *m = QueryAllBaseledgerTransactionResponse{} }
func (m *QueryAllBaseledgerTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllBaseledgerTransactionResponse) ProtoMessage()    {}
func (*QueryAllBaseledgerTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b223a452b70176, []int{5}
}
func (m *QueryAllBaseledgerTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBaseledgerTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBaseledgerTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBaseledgerTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBaseledgerTransactionResponse.Merge(m, src)
}
func (m *QueryAllBaseledgerTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBaseledgerTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBaseledgerTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBaseledgerTransactionResponse proto.InternalMessageInfo

func (m *QueryAllBaseledgerTransactionResponse) GetBaseledgerTransaction() []BaseledgerTransaction {
	if m != nil {
		return m.BaseledgerTransaction
	}
	return nil
}

func (m *QueryAllBaseledgerTransactionResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "Baseledger.baseledgerbridge.baseledger.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "Baseledger.baseledgerbridge.baseledger.QueryParamsResponse")
	proto.RegisterType((*QueryGetBaseledgerTransactionRequest)(nil), "Baseledger.baseledgerbridge.baseledger.QueryGetBaseledgerTransactionRequest")
	proto.RegisterType((*QueryGetBaseledgerTransactionResponse)(nil), "Baseledger.baseledgerbridge.baseledger.QueryGetBaseledgerTransactionResponse")
	proto.RegisterType((*QueryAllBaseledgerTransactionRequest)(nil), "Baseledger.baseledgerbridge.baseledger.QueryAllBaseledgerTransactionRequest")
	proto.RegisterType((*QueryAllBaseledgerTransactionResponse)(nil), "Baseledger.baseledgerbridge.baseledger.QueryAllBaseledgerTransactionResponse")
}

func init() { proto.RegisterFile("baseledger/query.proto", fileDescriptor_27b223a452b70176) }

var fileDescriptor_27b223a452b70176 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcf, 0x6a, 0x14, 0x31,
	0x18, 0xdf, 0x8c, 0xed, 0x1e, 0x22, 0x78, 0x88, 0x55, 0xcb, 0x22, 0xa3, 0x04, 0x6d, 0x45, 0x30,
	0xb1, 0x15, 0x7a, 0xa8, 0x28, 0x76, 0xc5, 0xf6, 0x60, 0x85, 0xba, 0xf4, 0xe4, 0x45, 0x32, 0x3b,
	0x21, 0x06, 0x66, 0x27, 0xd3, 0x49, 0x56, 0x5c, 0xc4, 0x83, 0x3e, 0x81, 0xe0, 0x1b, 0xf8, 0x16,
	0xbe, 0x41, 0xbd, 0x15, 0xbc, 0x78, 0x12, 0xd9, 0xf5, 0xe6, 0x43, 0x28, 0x9b, 0xa4, 0xce, 0x94,
	0x4e, 0x9d, 0x59, 0xff, 0xdc, 0x86, 0xcc, 0xf7, 0xfd, 0xfe, 0xe5, 0xfb, 0x02, 0xcf, 0x47, 0x4c,
	0xf3, 0x84, 0xc7, 0x82, 0xe7, 0x74, 0x6f, 0xc8, 0xf3, 0x11, 0xc9, 0x72, 0x65, 0x14, 0x5a, 0xea,
	0xfe, 0x3a, 0x27, 0x45, 0x49, 0x94, 0xcb, 0x58, 0xf0, 0xd2, 0x41, 0x67, 0x41, 0x28, 0xa1, 0x6c,
	0x0b, 0x9d, 0x7e, 0xb9, 0xee, 0xce, 0x45, 0xa1, 0x94, 0x48, 0x38, 0x65, 0x99, 0xa4, 0x2c, 0x4d,
	0x95, 0x61, 0x46, 0xaa, 0x54, 0xfb, 0xbf, 0xd7, 0xfb, 0x4a, 0x0f, 0x94, 0xa6, 0x53, 0x18, 0x47,
	0x4a, 0x9f, 0xaf, 0x44, 0xdc, 0xb0, 0x15, 0x9a, 0x31, 0x21, 0x53, 0x5b, 0xec, 0x6b, 0x2f, 0x94,
	0xf4, 0x65, 0x2c, 0x67, 0x83, 0x43, 0x90, 0xe5, 0xd2, 0x8f, 0xe2, 0xf3, 0xa9, 0xc9, 0x59, 0xaa,
	0x59, 0xbf, 0x40, 0xc0, 0x0b, 0x10, 0x3d, 0x9e, 0x72, 0xec, 0xd8, 0xee, 0x1e, 0xdf, 0x1b, 0x72,
	0x6d, 0x70, 0x1f, 0x9e, 0x3d, 0x72, 0xaa, 0x33, 0x95, 0x6a, 0x8e, 0xb6, 0x61, 0xdb, 0xb1, 0x2c,
	0x82, 0xcb, 0xe0, 0xda, 0xe9, 0x55, 0x42, 0x9a, 0xe5, 0x40, 0x1c, 0x4e, 0x77, 0x6e, 0xff, 0xcb,
	0xa5, 0x56, 0xcf, 0x63, 0xe0, 0x35, 0x78, 0xc5, 0x92, 0x6c, 0x71, 0x53, 0xc0, 0xec, 0x16, 0x0a,
	0xbd, 0x18, 0x74, 0x06, 0x06, 0x32, 0xb6, 0x8c, 0x73, 0xbd, 0x40, 0xc6, 0xf8, 0x3d, 0x80, 0x57,
	0x6b, 0x1a, 0xbd, 0xde, 0x11, 0x3c, 0x57, 0x59, 0xe0, 0xe5, 0xdf, 0x69, 0x2a, 0xbf, 0x12, 0xc4,
	0xbb, 0xa9, 0x66, 0xc0, 0xa9, 0x37, 0xb7, 0x91, 0x24, 0xbf, 0x35, 0xb7, 0x09, 0x61, 0x71, 0xab,
	0x5e, 0xd7, 0x12, 0x71, 0x23, 0x60, 0x25, 0x10, 0x37, 0x77, 0x7e, 0x04, 0xc8, 0x0e, 0x13, 0xdc,
	0xf7, 0xf6, 0x4a, 0x9d, 0xf8, 0xfb, 0x61, 0x28, 0x27, 0x13, 0xd6, 0x87, 0x72, 0xea, 0xff, 0x86,
	0x82, 0xb6, 0x8e, 0x98, 0x0d, 0xac, 0xd9, 0xe5, 0x5a, 0xb3, 0x4e, 0x77, 0xd9, 0xed, 0xea, 0xc7,
	0x79, 0x38, 0x6f, 0xdd, 0xa2, 0x0f, 0x00, 0xb6, 0xdd, 0x74, 0xa1, 0xf5, 0xa6, 0xca, 0x8f, 0x0f,
	0x7c, 0xe7, 0xf6, 0x1f, 0xf5, 0x3a, 0x65, 0x78, 0xed, 0xcd, 0xa7, 0x6f, 0xef, 0x82, 0x9b, 0x88,
	0xd0, 0x6e, 0xd5, 0xd6, 0x39, 0x10, 0x7a, 0x6c, 0x55, 0xd1, 0xeb, 0xe0, 0x84, 0xab, 0x40, 0xdb,
	0x33, 0xc9, 0xa9, 0x59, 0xa0, 0xce, 0xa3, 0x7f, 0x84, 0xe6, 0xed, 0x3e, 0xb4, 0x76, 0x1f, 0xa0,
	0xfb, 0x4d, 0xed, 0x56, 0x3f, 0x40, 0xf4, 0xa5, 0x8c, 0x5f, 0xa1, 0x1f, 0x00, 0x2e, 0x56, 0xd2,
	0x6d, 0x24, 0xc9, 0x8c, 0x31, 0xd4, 0xac, 0xda, 0x8c, 0x31, 0xd4, 0xed, 0x11, 0xde, 0xb4, 0x31,
	0xdc, 0x43, 0x77, 0xff, 0x2e, 0x86, 0xee, 0xee, 0xfe, 0x38, 0x04, 0x07, 0xe3, 0x10, 0x7c, 0x1d,
	0x87, 0xe0, 0xed, 0x24, 0x6c, 0x1d, 0x4c, 0xc2, 0xd6, 0xe7, 0x49, 0xd8, 0x7a, 0xb2, 0x2e, 0xa4,
	0x79, 0x36, 0x8c, 0x48, 0x5f, 0x0d, 0xaa, 0x39, 0x6e, 0x78, 0x92, 0x17, 0x65, 0x1a, 0x33, 0xca,
	0xb8, 0x8e, 0xda, 0xf6, 0x79, 0xbf, 0xf5, 0x33, 0x00, 0x00, 0xff, 0xff, 0xef, 0xed, 0x7a, 0xe2,
	0xc2, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a BaseledgerTransaction by id.
	BaseledgerTransaction(ctx context.Context, in *QueryGetBaseledgerTransactionRequest, opts ...grpc.CallOption) (*QueryGetBaseledgerTransactionResponse, error)
	// Queries a list of BaseledgerTransaction items.
	BaseledgerTransactionAll(ctx context.Context, in *QueryAllBaseledgerTransactionRequest, opts ...grpc.CallOption) (*QueryAllBaseledgerTransactionResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/Baseledger.baseledgerbridge.baseledger.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BaseledgerTransaction(ctx context.Context, in *QueryGetBaseledgerTransactionRequest, opts ...grpc.CallOption) (*QueryGetBaseledgerTransactionResponse, error) {
	out := new(QueryGetBaseledgerTransactionResponse)
	err := c.cc.Invoke(ctx, "/Baseledger.baseledgerbridge.baseledger.Query/BaseledgerTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BaseledgerTransactionAll(ctx context.Context, in *QueryAllBaseledgerTransactionRequest, opts ...grpc.CallOption) (*QueryAllBaseledgerTransactionResponse, error) {
	out := new(QueryAllBaseledgerTransactionResponse)
	err := c.cc.Invoke(ctx, "/Baseledger.baseledgerbridge.baseledger.Query/BaseledgerTransactionAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a BaseledgerTransaction by id.
	BaseledgerTransaction(context.Context, *QueryGetBaseledgerTransactionRequest) (*QueryGetBaseledgerTransactionResponse, error)
	// Queries a list of BaseledgerTransaction items.
	BaseledgerTransactionAll(context.Context, *QueryAllBaseledgerTransactionRequest) (*QueryAllBaseledgerTransactionResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) BaseledgerTransaction(ctx context.Context, req *QueryGetBaseledgerTransactionRequest) (*QueryGetBaseledgerTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseledgerTransaction not implemented")
}
func (*UnimplementedQueryServer) BaseledgerTransactionAll(ctx context.Context, req *QueryAllBaseledgerTransactionRequest) (*QueryAllBaseledgerTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseledgerTransactionAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Baseledger.baseledgerbridge.baseledger.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BaseledgerTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBaseledgerTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BaseledgerTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Baseledger.baseledgerbridge.baseledger.Query/BaseledgerTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BaseledgerTransaction(ctx, req.(*QueryGetBaseledgerTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BaseledgerTransactionAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllBaseledgerTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BaseledgerTransactionAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Baseledger.baseledgerbridge.baseledger.Query/BaseledgerTransactionAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BaseledgerTransactionAll(ctx, req.(*QueryAllBaseledgerTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Baseledger.baseledgerbridge.baseledger.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "BaseledgerTransaction",
			Handler:    _Query_BaseledgerTransaction_Handler,
		},
		{
			MethodName: "BaseledgerTransactionAll",
			Handler:    _Query_BaseledgerTransactionAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baseledger/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetBaseledgerTransactionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBaseledgerTransactionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBaseledgerTransactionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBaseledgerTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBaseledgerTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBaseledgerTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BaseledgerTransaction.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllBaseledgerTransactionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBaseledgerTransactionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBaseledgerTransactionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllBaseledgerTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBaseledgerTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBaseledgerTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.BaseledgerTransaction) > 0 {
		for iNdEx := len(m.BaseledgerTransaction) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BaseledgerTransaction[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetBaseledgerTransactionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetBaseledgerTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BaseledgerTransaction.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllBaseledgerTransactionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllBaseledgerTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BaseledgerTransaction) > 0 {
		for _, e := range m.BaseledgerTransaction {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBaseledgerTransactionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBaseledgerTransactionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBaseledgerTransactionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBaseledgerTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBaseledgerTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBaseledgerTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseledgerTransaction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseledgerTransaction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBaseledgerTransactionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBaseledgerTransactionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBaseledgerTransactionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBaseledgerTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBaseledgerTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBaseledgerTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseledgerTransaction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseledgerTransaction = append(m.BaseledgerTransaction, BaseledgerTransaction{})
			if err := m.BaseledgerTransaction[len(m.BaseledgerTransaction)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
